DROP TABLE CLIENTES IF EXISTS;
DROP TABLE PRODUCTOS IF EXISTS;
DROP TABLE RECIBO IF EXISTS;

CREATE TABLE CLIENTES (
IDCLIENT INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
FECHA DATE,
PRIMARY KEY(IDCLIENT)
);

CREATE TABLE PRODUCTOS (
IDPROD INT NOT NULL AUTO_INCREMENT,
MODELO VARCHAR(100),
PRECIO INT NOT NULL,
STOCK INT NOT NULL,
PRIMARY KEY(IDPROD)
);

CREATE TABLE RECIBO (
IDRECIBO INT NOT NULL AUTO_INCREMENT,
IDCLIENT INT NOT NULL,
CANTIDAD INT NOT NULL,
FECHA DATE,
TOTAL INT NOT NULL,
PRIMARY KEY(IDRECIBO)
);



